### ISSUE TITLE
using gmail

### ISSUE THREAD

**Issue by JaceDoile** [leXinshou/smtp-mail-luvit#1]
Hello, I'm new to smtp stuff, would it be possible for me to use Gmail smtp with this? if so could you please provide an example for Gmail usage. thanks.

**Comment by LeXinshou** [comment]
This is the full example for the email sending using gmail SMTP. 

```lua
local smtp = require("smtp")

local Mail = smtp:new({
    host = "smtp.gmail.com",
    port = 465,
    tls = true,
    isAuth = true
})


Mail:addAuth("your gmail address here", "Your password")
Mail:addMail("your gmail address here", "email that you want to send to")
Mail:addHead({
    from = "your name <myemail@>",
    to = "Email you are sending to <their address>",
    subject = "This is a  Subject"
})
Mail:addBody([[
    <h1>Hello World</h1>
]])

Mail:Send(function(text)
    p(text)
end)
```

If you still have any question, let me know.

**Comment by JaceDoile** [comment]
> This is the full example for the email sending using gmail SMTP.
> 
> ```lua
> local smtp = require("smtp")
> 
> local Mail = smtp:new({
>     host = "smtp.gmail.com",
>     port = 465,
>     tls = true,
>     isAuth = true
> })
> 
> 
> Mail:addAuth("your gmail address here", "Your password")
> Mail:addMail("your gmail address here", "email that you want to send to")
> Mail:addHead({
>     from = "your name <myemail@>",
>     to = "Email you are sending to <their address>",
>     subject = "This is a  Subject"
> })
> Mail:addBody([[
>     <h1>Hello World</h1>
> ]])
> 
> Mail:Send(function(text)
>     p(text)
> end)
> ```
> 
> If you still have any question, let me know.
thanks for the quick response, ill try it out in a little bit, thank you! also one more question in the addHead for from and to do i have to put the the text before the <email@domain> or can i leave it blank? sorry if my question doesnt make sense

**Comment by LeXinshou** [comment]
You can use a blank head if you wish to, it depends on the smtp server if they allow blank head. Currently, I haven't implemented nil safety to it, so you need to pass a empty string such as `" "`.

If you have seen your any email, you will notice it has a name before <..> you can use blank for it too if you just put only email there.

**Comment by JaceDoile** [comment]
> You can use a blank head if you wish to, it depends on the smtp server if they allow blank head. Currently, I haven't implemented nil safety to it, so you need to pass a empty string such as `" "`.
> 
> If you have seen your any email, you will notice it has a name before <..> you can use blank for it too if you just put only email there.

Alright cool, thanks man I appreciate you. much love <3
