### ISSUE TITLE
Uncaught error, attempt to call local 'write' (a string value)

### ISSUE THREAD

**Issue by JaceDoile** [leXinshou/smtp-mail-luvit#2]
When i try to use google smtp with the port 567 and tls set to false i get thrown this error.

```
Uncaught Error: ...s/Projects/LuvitLuaProjects/smtp/deps/smtp-mail/smtp.lua:82: attempt to call local 'write' (a string value)
stack traceback:
        ...s/Projects/LuvitLuaProjects/smtp/deps/smtp-mail/smtp.lua: in function 'Send'
        ...\Admin\Documents\Projects\LuvitLuaProjects\smtp\main.lua:20: in function 'fn'
        [string "bundle:deps/require.lua"]:310: in function 'require'
        [string "bundle:/main.lua"]:128: in function <[string "bundle:/main.lua"]:20>
stack traceback:
        [C]: in function 'error'
        ...cuments/Projects/LuvitLuaProjects/smtp/deps/coro-net.lua:29: in function <...cuments/Projects/LuvitLuaProjects/smtp/deps/coro-net.lua:26>
        [C]: in function 'run'
        [string "bundle:/init.lua"]:52: in function <[string "bundle:/init.lua"]:47>
        [C]: in function 'xpcall'
        [string "bundle:/init.lua"]:47: in function 'fn'
        [string "bundle:deps/require.lua"]:310: in function <[string "bundle:deps/require.lua"]:266>
```

the code im using is this

```lua
local smtp = require("smtp-mail")

local Mail = smtp:new({
    host = "smtp.gmail.com",
    port = 567,
    tls = false,
    isAuth = true
})


Mail:addAuth("gmail email", "app password") -- // Taken out my email and app password out for security reasons obviously
Mail:addMail("sender", "rec") -- // same here taken out emails
Mail:addHead({
    from = "<user@domain>",
    to = "<user@domain>",
    subject = "Testing"
})
Mail:addBody("Testing message.");

Mail:Send(function(text)
    p(text)
end)
```

Please get back to me

Btw, when i try with port 465 and tls set to true i dont get any output nor is an email sent and using the code above seems to be the only way google smtp works for me, not to sure, lmk if i've done anything wrong!

**Comment by JaceDoile** [comment]
btw you can contact me at ```Cosby#0222``` on discord if you would like me to go further in depth.

**Comment by LeXinshou** [comment]
I will test it as soon as possible and get back to you, this is a odd error, there probably some mistake happened.

**Comment by JaceDoile** [comment]
> I will test it as soon as possible and get back to you, this is a odd error, there probably some mistake happened.

Alright, coolio lmk. I'll check try and see what went wrong, ill have to read some documentation of the libraries that were used though, i'll lyk if i fix anything.

**Comment by LeXinshou** [comment]
The problem was invalid connection, unable to establish the connection returns such error.

Also, there might be some changes in SMTP usages, I will check soon. I have tried other smtp client, works pretty fine to me.
